name: pillar_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pip
  - numpy=2.2.2
  - pandas=2.2.3
  - seaborn=0.13.2

  - pip:
    - scikit-learn==1.6.1
    - fire
    - tqdm
    - ipykernel



